import type { ReaderDirectionTokens } from '../contract'

export const tokens = {
  light: {
    '--ll-paper': '#FFFFFF',
    '--ll-ink': '#141414',
    '--ll-secondary': '#4A4A4A',
    '--ll-rule': '#E2E0DC',
    '--ll-accent': '#9B2C2C',
    '--ll-panel': '#141414',
    '--ll-panel-ink': '#FFFFFF',
    '--ll-gold': '#C9A86A',
    '--ll-serif': 'var(--font-ll-serif), Georgia, serif',
    '--ll-sans': 'var(--font-ll-sans), Arial, sans-serif',
    '--ll-small': '0.8125rem',
    '--ll-label': '0.75rem',
    '--ll-body': '1.25rem',
    '--ll-dek': 'clamp(1.375rem, 1.1rem + 0.7vw, 1.875rem)',
    '--ll-card': 'clamp(1.625rem, 1.4rem + 0.4vw, 2rem)',
    '--ll-heading': 'clamp(2rem, 1.5rem + 1.5vw, 3rem)',
    '--ll-title': 'clamp(2.625rem, 1.6rem + 3.5vw, 5.25rem)',
    '--ll-cover-title': 'clamp(2.375rem, 1.4rem + 2.5vw, 4rem)',
    '--ll-wordmark': 'clamp(1.625rem, 1.2rem + 1.6vw, 3rem)',
    '--ll-dropcap': '3.7em',
    '--ll-leading': '1.65',
    '--ll-measure': '65ch',
    '--ll-page': '78rem',
    '--ll-gutter': 'clamp(1.25rem, 4vw, 4rem)',
    '--ll-space': 'clamp(3rem, 6vw, 6rem)',
  },
  dark: {
    '--ll-paper': '#1B1917',
    '--ll-ink': '#F5F0E9',
    '--ll-secondary': '#C7BEB4',
    '--ll-rule': '#4B4540',
    '--ll-accent': '#E59A91',
  },
  textPairs: [
    ['--ll-ink', '--ll-paper'],
    ['--ll-secondary', '--ll-paper'],
    ['--ll-accent', '--ll-paper'],
    ['--ll-panel-ink', '--ll-panel'],
    ['--ll-gold', '--ll-panel'],
  ],
} as const satisfies ReaderDirectionTokens
