import { defineDesignLabDirection } from './contract'
import {
  createArchiveDirectionViews,
  type ArchiveDirectionConfig,
} from './directions/archive-direction'
import type { DesignLabDirectionMetadata } from './types'

interface ArchiveDefinition extends ArchiveDirectionConfig {
  readonly id: string
  readonly metadata: DesignLabDirectionMetadata
}

const archiveDefinitions = [
  {
    accent: '#244edb',
    background: '#f0efe9',
    collection: 'Round 1 · Foundations',
    foreground: '#18202a',
    id: 'blue-pencil',
    label: 'LIVE BLUE MARGIN',
    layout: 'proof',
    metadata: {
      character: 'Warm paper, editorial blue, graphite notation, and restrained proof marks.',
      collection: 'Round 1 · Foundations',
      name: 'Blue Pencil',
      order: 'A1',
      ownerFit: 'Excellent writing confidence and a premium literary voice.',
      risk: 'Can feel too literary when image-led stories dominate the issue.',
      signature: 'A live blue editorial margin explains state without becoming a dashboard.',
      thesis: 'A calm proofing room where every story feels like a carefully marked galley.',
    },
    muted: '#556170',
    name: 'Blue Pencil',
    panel: '#fffdf8',
    signal: 'PROOF',
  },
  {
    accent: '#ed3e86',
    background: '#151821',
    collection: 'Round 1 · Foundations',
    foreground: '#f5f2ea',
    id: 'light-table',
    label: 'LUMINOUS MEDIA RAIL',
    layout: 'image',
    metadata: {
      character: 'Charcoal glass, gallery white, magenta annotation, and luminous photography.',
      collection: 'Round 1 · Foundations',
      name: 'Light Table',
      order: 'A2',
      ownerFit: 'Best for photography-led stories, sequencing, and visible art direction.',
      risk: 'Long writing sessions need careful dark-mode contrast tuning.',
      signature: 'A luminous media rail keeps imagery inside the writing process.',
      thesis: 'A cinematic, image-first studio built around contact sheets and visual sequence.',
    },
    muted: '#9da4b4',
    name: 'Light Table',
    panel: '#232735',
    signal: 'FRAME',
  },
  {
    accent: '#a92723',
    background: '#e9e7df',
    collection: 'Round 1 · Foundations',
    foreground: '#111111',
    id: 'edition-zero',
    label: 'ISSUE REGISTER / 00',
    layout: 'system',
    metadata: {
      character: 'Swiss white, registration black, lacquer red, and dense editorial metadata.',
      collection: 'Round 1 · Foundations',
      name: 'Edition Zero',
      order: 'A3',
      ownerFit: 'Fast scanning, operational clarity, and a credible path to multiple editors.',
      risk: 'The information density needs warm language to avoid feeling stern.',
      signature: 'An issue clock and numbered story register make publication flow tangible.',
      thesis: 'A rigorous Swiss publishing desk: direct, fast, and intentionally information-rich.',
    },
    muted: '#5e5d58',
    name: 'Edition Zero',
    panel: '#f8f6ef',
    signal: '07:18',
  },
  {
    accent: '#5940b8',
    background: '#eeeae5',
    collection: 'Round 1 · Foundations',
    foreground: '#2a2630',
    id: 'margin-studio',
    label: 'SOFT MARGIN DRAWER',
    layout: 'studio',
    metadata: {
      character: 'Parchment, aubergine, soft lilac, mint details, and generous empty space.',
      collection: 'Round 1 · Foundations',
      name: 'Margin Studio',
      order: 'A4',
      ownerFit: 'The lowest cognitive load for a nontechnical solo owner.',
      risk: 'Progressively disclosed controls must remain easy to rediscover.',
      signature: 'A soft margin drawer turns publishing checks into calm guidance.',
      thesis: 'A quiet creative room that removes administration until the owner needs it.',
    },
    muted: '#5d5661',
    name: 'Margin Studio',
    panel: '#fffefa',
    signal: 'WARM',
  },
  {
    accent: '#f2d948',
    background: '#101417',
    collection: 'Round 1 · Foundations',
    foreground: '#f1f2ed',
    id: 'pressroom',
    label: 'LIVE EDITORIAL STATUS',
    layout: 'press',
    metadata: {
      character: 'News ink, industrial white, warning yellow, and live production typography.',
      collection: 'Round 1 · Foundations',
      name: 'Pressroom',
      order: 'A5',
      ownerFit: 'Strong cadence, schedule visibility, and future editorial operations.',
      risk: 'Operational energy can overpower intimate long-form writing.',
      signature: 'A run-of-show board connects each story to the next edition.',
      thesis: 'A confident live newsroom where lifecycle state is visible at a glance.',
    },
    muted: '#9aa4aa',
    name: 'Pressroom',
    panel: '#1c2226',
    signal: 'LIVE',
  },
  {
    accent: '#a72b3d',
    background: '#e9e4db',
    collection: 'Round 2 · Studio Systems',
    foreground: '#211d27',
    id: 'galley-27',
    label: 'GALLEY / 27',
    layout: 'proof',
    metadata: {
      character: 'Plum ink, coral proof marks, oat paper, and an authored editorial margin.',
      collection: 'Round 2 · Studio Systems',
      name: 'Galley 27',
      order: 'B1',
      ownerFit: 'Highest writing confidence with an unmistakable magazine identity.',
      risk: 'Image-heavy workflows need the media drawer one gesture away.',
      signature: 'A living proof margin turns system state into editorial guidance.',
      thesis: 'An editorial atelier where writing, proofing, and publication share one surface.',
    },
    muted: '#5a525c',
    name: 'Galley 27',
    panel: '#fffcf5',
    signal: '27',
  },
  {
    accent: '#7be7ff',
    background: '#11181c',
    collection: 'Round 2 · Studio Systems',
    foreground: '#f4f5ef',
    id: 'aperture',
    label: 'LIGHT TABLE / ACTIVE',
    layout: 'image',
    metadata: {
      character: 'Cinema black, cold cyan, projected white, and full-bleed photography.',
      collection: 'Round 2 · Studio Systems',
      name: 'Aperture',
      order: 'B2',
      ownerFit: 'The strongest art-direction and visual-storytelling workspace.',
      risk: 'The immersive shell requires careful tuning for long writing sessions.',
      signature: 'The light table remains spatially present while the owner writes.',
      thesis: 'A cinematic visual studio where the issue is composed through image and atmosphere.',
    },
    muted: '#9aa9af',
    name: 'Aperture',
    panel: '#1c272c',
    signal: 'OPEN',
  },
  {
    accent: '#ff7a47',
    background: '#152942',
    collection: 'Round 2 · Studio Systems',
    foreground: '#eef6ff',
    id: 'live-issue',
    label: 'CONTINUOUS RELEASE LINE',
    layout: 'system',
    metadata: {
      character: 'Deep broadcast blue, signal orange, clear cyan, and kinetic issue markers.',
      collection: 'Round 2 · Studio Systems',
      name: 'Live Issue',
      order: 'B3',
      ownerFit: 'The clearest scheduling model and strongest future team scalability.',
      risk: 'Operational momentum must not crowd out intimate writing focus.',
      signature: 'A continuous release line joins today’s writing to the next edition.',
      thesis: 'A kinetic publishing system that makes cadence, state, and readiness tangible.',
    },
    muted: '#9cb2ca',
    name: 'Live Issue',
    panel: '#1c3856',
    signal: 'NEXT',
  },
  {
    accent: '#1749b8',
    background: '#dfe3e5',
    collection: 'Round 3 · Refined Instruments',
    foreground: '#172027',
    id: 'mercury',
    label: 'REFLECTIVE ISSUE RAIL',
    layout: 'studio',
    metadata: {
      character: 'Brushed silver, soft ink, electric blue, and reflective interface materials.',
      collection: 'Round 3 · Refined Instruments',
      name: 'Mercury',
      order: 'C1',
      ownerFit: 'A calm writing surface with guidance appearing only when useful.',
      risk: 'Metallic material cues must remain restrained rather than ornamental.',
      signature: 'A reflective issue rail carries publication state through every screen.',
      thesis: 'A cool editorial instrument in brushed silver, soft ink, and electric blue.',
    },
    muted: '#4e5d67',
    name: 'Mercury',
    panel: '#f6f8f8',
    signal: 'SAFE',
  },
  {
    accent: '#c20f20',
    background: '#f2efe9',
    collection: 'Round 3 · Refined Instruments',
    foreground: '#0f0f10',
    id: 'cutline',
    label: 'IMAGE / TYPE / RELEASE',
    layout: 'press',
    metadata: {
      character:
        'High-fashion black, bone white, lacquer red, and aggressively cropped photography.',
      collection: 'Round 3 · Refined Instruments',
      name: 'Cutline',
      order: 'C2',
      ownerFit: 'The strongest authored identity with a disciplined writing mode.',
      risk: 'The dramatic desk must not make ordinary owner actions feel intimidating.',
      signature: 'Photography slices through the typographic grid instead of sitting in cards.',
      thesis: 'A high-fashion editorial room built from hard cuts, black ink, and one red signal.',
    },
    muted: '#676363',
    name: 'Cutline',
    panel: '#fffdf8',
    signal: 'CUT',
  },
  {
    accent: '#b9ff68',
    background: '#15152a',
    collection: 'Round 3 · Refined Instruments',
    foreground: '#f5f4ff',
    id: 'edition-os',
    label: 'EDITION LINE / ONLINE',
    layout: 'system',
    metadata: {
      character: 'Midnight violet, phosphor green, ice blue, and precise temporal navigation.',
      collection: 'Round 3 · Refined Instruments',
      name: 'Edition OS',
      order: 'C3',
      ownerFit: 'Always communicates what is being written, ready, and next.',
      risk: 'The operating-system metaphor must remain human and editorial.',
      signature: 'A continuous edition line makes time and readiness the navigation system.',
      thesis: 'A sleek publishing instrument connecting editorial rhythm, state, and release.',
    },
    muted: '#a9a8c1',
    name: 'Edition OS',
    panel: '#242442',
    signal: 'SYNC',
  },
] as const satisfies readonly ArchiveDefinition[]

export const archiveDesignLabDirections = archiveDefinitions.map((definition) => {
  const views = createArchiveDirectionViews(definition)
  return defineDesignLabDirection({
    id: definition.id,
    metadata: definition.metadata,
    views: { desk: views.Desk, reader: views.Reader, write: views.Write },
  })
})
