import type { ReaderDirectionTokens } from '../contract'

export const tokens = {
  light: {
    '--cf-ground': '#0B0C0C',
    '--cf-ink': '#F2F1EC',
    '--cf-secondary': '#CFCDC5',
    '--cf-amber': '#E6B65C',
    '--cf-slate': '#4F5B66',
    '--cf-paper': '#F2F1EC',
    '--cf-body-ink': '#151515',
    '--cf-body-secondary': '#4F5B66',
    '--cf-body-accent': '#755017',
    '--cf-sans': 'var(--font-cf-sans), Arial, sans-serif',
    '--cf-mono': 'var(--font-cf-mono), monospace',
    '--cf-label': '0.6875rem',
    '--cf-small': '0.75rem',
    '--cf-copy': '1rem',
    '--cf-body': '1.25rem',
    '--cf-card': 'clamp(2rem, 1.3rem + 2vw, 3.75rem)',
    '--cf-dek': 'clamp(1.125rem, 1rem + 0.6vw, 1.625rem)',
    '--cf-heading': 'clamp(2rem, 1.5rem + 2vw, 3.5rem)',
    '--cf-title': 'clamp(3.25rem, 1.5rem + 6vw, 7.5rem)',
    '--cf-wordmark': '1.5rem',
    '--cf-leading': '1.7',
    '--cf-measure': '65ch',
    '--cf-page': '90rem',
    '--cf-gutter': 'clamp(1.25rem, 4vw, 4rem)',
    '--cf-space': 'clamp(3.5rem, 7vw, 7rem)',
  },
  dark: {
    '--cf-paper': '#0B0C0C',
    '--cf-body-ink': '#F2F1EC',
    '--cf-body-secondary': '#CFCDC5',
    '--cf-body-accent': '#E6B65C',
  },
  textPairs: [
    ['--cf-ink', '--cf-ground'],
    ['--cf-secondary', '--cf-ground'],
    ['--cf-amber', '--cf-ground'],
    ['--cf-body-ink', '--cf-paper'],
    ['--cf-body-secondary', '--cf-paper'],
    ['--cf-body-accent', '--cf-paper'],
  ],
} as const satisfies ReaderDirectionTokens
