DROP TABLE IF EXISTS article_search_documents;
DROP TABLE IF EXISTS idempotency_records;
DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS outbox_events;
DROP TABLE IF EXISTS publishing_jobs;
ALTER TABLE IF EXISTS reusable_blocks DROP CONSTRAINT IF EXISTS reusable_blocks_current_revision_fk;
DROP TABLE IF EXISTS reusable_block_revisions;
DROP TABLE IF EXISTS reusable_blocks;
DROP TABLE IF EXISTS media_renditions;
DROP TABLE IF EXISTS media_assets;
DROP TABLE IF EXISTS slug_redirects;
DROP TABLE IF EXISTS article_taxonomies;
DROP TABLE IF EXISTS taxonomies;
DROP TABLE IF EXISTS article_autosaves;
ALTER TABLE IF EXISTS articles DROP CONSTRAINT IF EXISTS articles_scheduled_revision_fk;
ALTER TABLE IF EXISTS articles DROP CONSTRAINT IF EXISTS articles_published_revision_fk;
ALTER TABLE IF EXISTS articles DROP CONSTRAINT IF EXISTS articles_current_draft_revision_fk;
DROP TABLE IF EXISTS article_revisions;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS publication_settings;
